matrix:
  include:
  - os: osx
    osx_image: xcode9.3
    language: node_js
    node_js: '10'
    env:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
  - os: linux
    services: docker
    language: generic
cache:
  directories:
  - node_modules
  - "$HOME/.cache/electron"
  - "$HOME/.cache/electron-builder"
before_install:
- |
  if [ "$TRAVIS_OS_NAME" == "osx" ]; then
    mkdir -p /tmp/git-lfs && curl -L https://github.com/github/git-lfs/releases/download/v2.3.1/git-lfs-$([ "$TRAVIS_OS_NAME" == "linux" ] && echo "linux" || echo "darwin")-amd64-2.3.1.tar.gz | tar -xz -C /tmp/git-lfs --strip-components 1
    export PATH="/tmp/git-lfs:$PATH"
  fi
before_script:
- git lfs pull
script:
- |
  if [ "$TRAVIS_OS_NAME" == "linux" ]; then
    docker run --rm \
      --env-file <(env | grep -iE 'DEBUG|NODE_|ELECTRON_|YARN_|NPM_|CI|CIRCLE|TRAVIS|APPVEYOR_|CSC_|_TOKEN|_KEY|AWS_|STRIP|BUILD_') \
      -v ${PWD}:/project \
      -v ~/.cache/electron:/root/.cache/electron \
      -v ~/.cache/electron-builder:/root/.cache/electron-builder \
      electronuserland/builder:wine \
      /bin/bash -c "yarn --link-duplicates --pure-lockfile && yarn release --linux --win"
  else
    yarn release
  fi
before_cache:
- rm -rf $HOME/.cache/electron-builder/wine
branches:
  except:
  - "/^v\\d+\\.\\d+\\.\\d+$/"
env:
  global:
    secure: COYcUC9d6jsc+eGAWGny+Ir/qNz8E/dTw9THVEXHZ9QGpeCzfS/bL8G8wo1CEM2zpuG3tgf6997S/ATq0Z7p9YxknfId5DL3K0Pei2vDo4AaMnXiNdytVjNB36yUTn+W/Gpw0tCnD23RSgQHsaTZX3NE0/USoiWmHf+nmLR9lbwHZsqFXYEjh/2Tkd39QAjfcLXmAOw6O+NTHElcAq5PrSOfPDfwdXnTwkZCl2DaQtvOJ4zSsuemEsknrAZCw6G2f5intu4QpvVm2FGAxHsm5BI5NvJDSzYaRU5D/ub6diDUJEZaDsTueJG65MKqjIEB9YZBQuLEk3PspF2SBIeI8jP/wkHY6rjPRrtmbWKF0M6rvfw0BMNqRY4d0VVvKD33XjmNlhYAeVpRJhaTuhNru/PzuCcxSmNnB2ywahVtIXs9h5DC8stfOxkseLM3Da+LFyLBaoGNjoLCFqdQOUny0XzxuQnu89zfOVfA60PTZTPNU5xbxVj/EbVsZau31cGSU9OF7NqH2k4T2CDCdSrOUlAF//ha6bVuLNcOR+KKxM0M+G6R4GJfa+ffNEcCMmB6iyauCoCVrCa+w2Vse9c0gDQV5NFLAmWNWZPbnBPSU+iCqZKTI3UicXixZxskq/rDb/SCT2aLipqnM277++Ty637eXC6lXXT3zbeluJFG4ho=
